package service

import "time"

// Joke of the day.
//
// The list lives HERE, not in the app, because the daily push needs the same
// text the screen shows. Two copies would drift the first time one was edited,
// and the push is the copy people actually read.
//
// Shorter than 365 on purpose: a full year of distinct pickleball jokes means
// the last hundred are filler, and a weak joke today costs more than a repeat
// months from now. Appending is safe — nothing depends on the length.
var pickleballJokes = []string{
	"Why did the pickleball player bring a ladder? Heard the competition was on another level.",
	"I told my wife I'd be home after one game. That was three hours and four paddles ago.",
	"My doctor said to avoid stress. So I quit my job and took up pickleball. Now I have neither money nor peace.",
	"Pickleball: the only sport where 'kitchen' is a place you're not allowed to stand.",
	"I'm not addicted to pickleball. I can stop whenever the courts close.",
	"What's a pickleball player's favourite meal? Anything, as long as it's eaten between games.",
	"Why don't pickleball players ever get lost? They always know where the baseline is.",
	"My partner said 'yours!' I said 'ours!' The ball said nothing and landed between us.",
	"Pickleball is 10% skill, 20% strategy, and 70% deciding whose ball that was.",
	"I bought a new paddle to fix my game. Turns out the paddle wasn't the problem.",
	"Why is it called pickleball? Because 'mildly-athletic-chess-with-a-wiffle-ball' didn't fit on the sign.",
	"My third shot drop is more of a third shot suggestion.",
	"Nothing ages a person faster than a 19-year-old saying 'nice shot, sir.'",
	"I've never met a pickleball player who thought the score was what the other team said it was.",
	"The kitchen is the only room in my life I'm actively avoiding.",
	"Pickleball rule one: the ball is always closer to your partner. Ask them, they'll disagree.",
	"I don't have a signature shot. I have a signature apology.",
	"Why did the pickleball go to therapy? It kept getting hit by people it trusted.",
	"Marriage counselling is expensive. Mixed doubles is free and achieves the same clarity.",
	"My DUPR went down 0.03 and I've thought about nothing else for six days.",
	"What do you call a pickleball player with no partner? A wall enthusiast.",
	"The scoreboard says 7-4-2. My brain says 'sure, why not.'",
	"I lobbed my opponent once. He hasn't forgiven me and it's been two seasons.",
	"Why are pickleball players so calm? All the yelling happens between points.",
	"My warm-up routine is complaining about my knees until someone serves.",
	"I told him it was out. The line told a different story. We're no longer speaking.",
	"Pickleball is the only place where 'let's play one more' is a legally binding lie.",
	"A pickleball paddle walks into a bar. The bartender says 'you look a bit dinky.'",
	"What's the hardest part of pickleball? Explaining to your family why you own four paddles.",
	"I have two speeds: dinking, and panicking while dinking.",
	"My opponent apologised for the net cord. His face said otherwise.",
	"Why did the player refuse to leave the kitchen? He said he was making a stand. He was faulted.",
	"The best pickleball advice I ever got: stop hitting it to the good one.",
	"I don't keep score. I keep grudges.",
	"Pickleball: where a 70-year-old will beat you and then help you up.",
	"Why don't pickleball players play hide and seek? Because someone always calls it out.",
	"I've spent more on paddles than on my first car. My first car was worse at the kitchen line.",
	"My serve is consistent. Consistently a warning to my partner.",
	"What do you call a perfect dink rally? Twelve seconds of silence followed by someone's shoulder.",
	"The ball was in. My opponent knows the ball was in. The ball knows. We are choosing peace.",
	"I signed up for a beginner clinic and got humbled by a man wearing jeans.",
	"Why is the third shot so hard? Because the first two went so well you got confident.",
	"My paddle has a sweet spot. I have visited it twice.",
	"Pickleball players don't retire. They just move to a court with more shade.",
	"The two hardest things in life: losing a loved one, and losing to someone who says 'lucky shot.'",
	"I called a timeout to think. It didn't help but the sitting was nice.",
	"What's a pickleball player's love language? Poaching, apparently.",
	"I've been told my footwork is 'creative.'",
	"There are two kinds of pickleball players: those who warm up, and those who are injured.",
	"Nothing unites strangers like agreeing the guy on court three is lobbing too much.",
	"My favourite shot is the one my opponent hits into the net.",
	"Why did the pickleball player bring a pencil? To draw the line his opponent kept ignoring.",
	"I'm not slow. The ball is just early.",
	"The kitchen line is a suggestion the way a speed limit is a suggestion. Both end in consequences.",
	"I got an ace. It was a mishit. I accepted the compliment anyway.",
	"Pickleball is chess if chess had ankle injuries.",
	"My partner poached, missed, and said 'I had that.' We are discussing it in the car.",
	"The scariest sound in pickleball is a paddle being tapped in appreciation of your unforced error.",
	"I bought grip tape to improve my game. My game noticed nothing.",
	"Why do pickleball players make good neighbours? They're always at the courts.",
	"The most competitive sentence in sport: 'we're just playing for fun.'",
	"A dink is just a smash that thought better of it.",
	"I have never once agreed with a line call that went against me. Statistically that's suspicious.",
	"My knees have opinions about my paddle sports schedule.",
	"What's worse than losing 11-0? Losing 11-0 to someone who says 'good games' with a straight face.",
	"I switched to a heavier paddle and now my elbow files complaints.",
	"The best part of pickleball is the community. The worst part is the community's line calls.",
	"Why did the pickleball player carry two paddles? One for playing, one for hope.",
	"I've been playing for a year. I'm now confidently bad instead of nervously bad.",
	"A stacked formation is when you and your partner are both confused in an organised way.",
	"The Erne is named after a man who realised the rules never said you couldn't.",
	"My opponent said 'nice get.' I was falling over. I'll take it.",
	"Pickleball scoring exists to make sure at least one person is always wrong.",
	"I'd rather lose a close one than win against someone who won't stop explaining what I did wrong.",
	"The court is 20 by 44 feet. My comfort zone is roughly a beach towel in the middle.",
	"Why did the player smash a dink? He'd had a long week.",
	"My paddle is carbon fibre. My reflexes are not.",
	"The most honest moment in pickleball is the half-second after you hit it out.",
	"I don't get nervous. I get 'suddenly unable to serve.'",
	"Round robin: a format designed so everyone can lose to everyone equally.",
	"What do you call four retirees at 7am on a Tuesday? A sold-out fixture.",
	"I got a paddle for my birthday and a lesson for my ego.",
	"Never trust a player who arrives with their own ball and a strong opinion about it.",
	"My strategy is to hit it to the middle and let them sort it out.",
	"The kitchen: where dreams go to be volleyed politely back and forth.",
	"I'm working on my patience. Currently at four dinks before I do something stupid.",
	"Why don't pickleball players lie? The line judge is everyone.",
	"A tournament is just a very expensive way to find out what your backhand does under pressure.",
	"My backhand has two settings: absent and apologetic.",
	"The only thing faster than a pickleball is the excuse that follows it.",
	"I've made peace with my ceiling. My ceiling is 3.5 and it is comfortable up there.",
	"What did the paddle say to the ball? 'This is going to sting a bit for both of us.'",
	"Pickleball taught me that I am, at heart, a person who blames equipment.",
	"The team that talks the most usually wins. Or at least enjoys losing more.",
	"I hit a winner and celebrated. It was out. The celebration was not retracted in time.",
	"Why are pickleball courts so friendly? Everyone's within shouting distance and chooses not to.",
	"My serve toss is inconsistent, which is impressive given there isn't one.",
	"Doubles is a trust exercise where one person keeps failing the exercise.",
	"The difference between 3.0 and 4.0 is knowing which mistake you're about to make.",
	"I don't need a coach. I need someone to stop me hitting the low-percentage one.",
	"Pickleball: the only sport where the warm-up is longer than some of the games.",
	"A let serve used to be a replay. Now it's a small tragedy we all move on from.",
	"My favourite pickleball moment is the silence right before someone argues about the score.",
	"I've been told to 'move my feet.' I've considered it.",
	"The paddle bag is not for paddles. It's for the four water bottles I never drink.",
	"Why did the pickleball player start meditating? To survive the third game.",
	"Every group has one person who calls the score wrong with total confidence.",
	"I once won a point by falling over. I'll be repeating the technique.",
	"Pickleball is the fastest-growing sport because standing still is optional.",
	"You know it's serious when someone brings a second shirt.",
	"My drop shot has a 30% success rate and 100% commitment.",
	"The hardest shot in pickleball is the one where you have time to think.",
	"Nothing sharpens the mind like your partner saying 'switch' at the last possible second.",
	"I've stopped counting rallies. I've started counting recoveries.",
	"The kitchen line is where good intentions go to be faulted.",
	"Why do pickleball players love the wind? They don't. Nobody does. Nobody ever has.",
	"A close game builds character. I have enough character now, thanks.",
	"I told my partner to poach more. He poached everything, including my confidence.",
	"The court is small until you're the one running to the corner.",
	"My greatest strength is enthusiasm. My greatest weakness is also enthusiasm.",
	"You don't lose to a lobber. You lose to yourself, slowly, while backpedalling.",
	"Pickleball has taught me humility, mostly through repetition.",
	"The most powerful phrase in doubles: 'that's on me.' Use it early and often.",
	"Why did the player bring a notebook? To write down the score nobody agreed on.",
	"I've reached the stage where I stretch before I stretch.",
	"A good partner tells you 'nice try.' A great partner says nothing and covers the middle.",
	"The score is 4-3-2 and I have never been less sure of anything in my life.",
	"I bought a lighter paddle for control and immediately hit everything long.",
	"What's the loneliest place in pickleball? The transition zone.",
	"The no-man's-land is well named. Nobody wants it and everybody stands there.",
	"I've never seen a rally end because someone ran out of ideas. Only patience.",
	"Pickleball players don't have off-seasons, they have indoor seasons.",
	"My paddle's warranty covers manufacturing defects, not the decisions I make with it.",
	"Why did the pickleball player win the argument? He didn't. He just kept serving.",
	"A rally with no unforced errors is a rumour I've heard about but not witnessed.",
	"You learn a lot about someone in a tiebreak.",
	"The best players make it look easy. The rest of us make it look like a lot.",
	"I've been working on my consistency. Consistently, and without results.",
	"Pickleball is the only sport where 'just get it in' is elite strategy.",
	"What's the difference between a lob and a betrayal? Timing.",
	"I've apologised more on a pickleball court than in the rest of my life combined.",
	"The paddle tap after a game is a peace treaty and everyone knows it.",
	"Why did the beginner beat the intermediate? Because the intermediate got fancy.",
	"Getting older is fine. Getting lobbed is the problem.",
	"My reflexes at the kitchen are excellent, roughly one shot after they're needed.",
	"The most dangerous player on the court is the one who doesn't miss.",
	"I don't play mind games. My mind plays them without me.",
	"Every pickleball group has one person who knows the rules and one who is confident.",
	"Rain delays are just group chats with extra opinions.",
	"I've never regretted going to play. I have regretted the fourth game.",
	"A pickleball is 26 holes of pure judgement.",
	"The wiffle ball was invented for backyards and somehow became a lifestyle.",
	"Why don't pickleballs get invited to parties? Too many holes in their stories.",
	"My paddle grip is 4 1/8 inches and I will tell you about it unprompted.",
	"The best shot in pickleball is the one your opponent didn't expect. Including you.",
	"I've watched hours of instructional videos and improved by one shot, possibly coincidentally.",
	"There's no crying in pickleball. There is, however, a lot of sighing.",
	"The scoreboard is a suggestion until someone writes it down.",
	"You can tell a lot about a player by how they handle a bad bounce.",
	"I came for the exercise and stayed for the arguing about whether it was in.",
	"Why did the pickleball player buy new shoes? The old ones had learned his mistakes.",
	"My footwork improved dramatically the day I stopped watching my feet.",
	"A dink war is just two people politely refusing to make the first mistake.",
	"The greatest athletes in pickleball are the ones who can wait.",
	"I've been playing three years and I still flinch at body shots.",
	"The person who says 'no worries' after your error is the person keeping count.",
	"Pickleball is the only sport where a 4-foot rule causes 40 minutes of debate.",
	"I don't need to win. I just need the other team to know it was close.",
	"Nothing is more optimistic than a between-the-legs attempt down 10-2.",
	"The paddle is an extension of your arm, and mine has inherited all its flaws.",
	"I've stopped saying 'last game.' Nobody believes me and it damages my credibility.",
	"Every court has an unofficial mayor and you will meet them within four minutes.",
	"A pickleball tournament is a family reunion where everyone is trying to beat you.",
	"The secret to pickleball is patience. I'm told. Repeatedly. While losing.",
	"I've had better days on the court, but I've had worse ones in meetings.",
	"The point of pickleball isn't winning. That's just where the fun happens to be.",
}

// JokeOfTheDay returns the joke for [t]'s day, the same for everyone.
//
// Keyed on day-of-year rather than random: a joke that changes when you
// pull-to-refresh isn't a joke of the DAY, and two people on the same court
// should be reading the same one.
func JokeOfTheDay(t time.Time) string {
	if len(pickleballJokes) == 0 {
		return ""
	}
	return pickleballJokes[t.YearDay()%len(pickleballJokes)]
}

// JokeCount is how many are in rotation, for the /joke endpoint's metadata.
func JokeCount() int { return len(pickleballJokes) }
